language: cpp

sudo: false

dist: trusty

compiler:
  - gcc

branches:
  only:
    - master
    - v1.5-dev
    - master_travis

os:
  - linux
  - osx

before_install:
  - $CXX --version
  - $CC --version

  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -qq update; fi

  # OS X: update brew cache:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$CC" == "gcc" ]]; then CC=gcc-4.9; fi
  
install:
  # Install package dependencies for Linux:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y libusb-1.0-0 libusb-1.0-0-dev python2.7 python-numpy cmake qt4-dev-tools root-system; fi

  # Install package dependencies for Mac OS X:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install python libusb homebrew/science/root; fi
  # Install numpy via pip:
  - if [ $TRAVIS_OS_NAME == osx ]; then easy_install pip && pip install numpy; fi

before_script:
  
  # For Mac OS X we still need to source the root environment:
  - if [ $TRAVIS_OS_NAME == osx ]; then source $(brew --prefix root)/libexec/thisroot.sh; fi

  - $CXX --version
  - $CC --version

  - cd build

script:
  - cmake -DBUILD_onlinemon=OFF ..
  - make install

